

export enum HangupResultEnum {

    JOB_CANCELED = 'JOB_CANCELED',
    LOCAL_SIP_CANCELED = 'LOCAL_SIP_CANCELED',
    REMOTE_SIP_CANCELED = 'REMOTE_SIP_CANCELED',
    LOCAL_HANGUP = 'LOCAL_HANGUP',
    REMOTE_HANGUP = 'REMOTE_HANGUP'


}